# Generated by Django 5.0.2 on 2024-02-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridgeo', '0003_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
